### PR TITLE
Room test

### PR DESCRIPTION
**Pull request by Charidan**
Made pressure plate and door and hooked them together

### CODE REVIEW

**Comment by alexander-l-stone** [comment]
This currently does not let us dynamically attach pressure plates to doors, but instead has the pressure plate affect the door. Maybe we should try using the export function built into GDScript to allow us to set the target of the pressure plate from the editor(I don't think the door needs changes)

**Review by alexander-l-stone — COMMENTED** [review]
See the comment I left above.

**Comment by alexander-l-stone** [comment]
Door speed should also be an exported variable.

**Comment by Charidan** [comment]
Pressure plates should fire a signal that doors can listen for

**Pull request merged**
